spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/rent_now
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
